server:
  port: 8085

spring:
   datasource:
     platform: postgres
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/Distribuida
     username: postgres
     password: admin
